name: Publish Submission

on:
  pull_request_target:
    paths:
      - submissions/*.py
    types:
      - closed

jobs:

  publish-submission:
  
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - name: (Re)Evaluation
      timeout-minutes: 10
      run: |
        stdbuf -oL \
        python test_strategy.py \
        --author ${{ github.event.pull_request.user.login }} \
        --catch-errors --publish --summary $GITHUB_STEP_SUMMARY
      
    - name: Commit updates
      uses: EndBug/add-and-commit@v9
      with:
        add: "--all"
        author_name: GitHub Action
        author_email: action@github.com
        message: "Publishing ${{ github.event.pull_request.user.login }}'s solution."
        push: true